### ISSUE TITLE
Unable to integrate Google OAuth - response.headers?.entries is not a function

### ISSUE THREAD

**Issue by lyra-white** [spoonjoy/redwoodjs-dbauth-oauth-web#3]
Log on the console:

```
api | 20:43:41 🌲 request completed 201ms
api | 20:44:20 🌲 incoming request GET xxx /auth/oauth?method=signupWithGoogle&state=http%3A%2F%2Flocalhost%3A3007%2Flogin&code=4%2F0AeanS0bEo-h85GtxcJU_hz4rSOz35bz_ypQ1FLy8Brrq7SiBIqVAPDg1q0utQAfVvjFNuQ&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&authuser=0&prompt=none
api | 20:44:20 🚨 response.headers?.entries is not a function 
api | 
api | 🚨 TypeError Info
api | 
api | {}
api |  
api | 🥞 Error Stack
api | 
api | TypeError: response.headers?.entries is not a function
api |     at OAuthHandler.createResponse (/path/to/project/node_modules/@spoonjoy/redwoodjs-dbauth-oauth-api/node_modules/@redwoodjs/auth-dbauth-api/dist/shared.js:214:47)
api |     at OAuthHandler.<anonymous> (/path/to/project/node_modules/@spoonjoy/redwoodjs-dbauth-oauth-api/dist/OAuthHandler.js:967:33)
api |     at Generator.throw (<anonymous>)
api |     at rejected (/path/to/project/node_modules/@spoonjoy/redwoodjs-dbauth-oauth-api/dist/OAuthHandler.js:29:65)
api |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
api | 
api | 20:44:20 🌲 request completed 109ms
```

Settings:

```
FE_URL="http://localhost:3007"
RWJS_API_URL="http://localhost:8917"

GOOGLE_CLIENT_ID = "MY-CLIENT-ID"
GOOGLE_CLIENT_SECRET = "MY-CLIENT-SECRET"
GOOGLE_REDIRECT_URL="http://localhost:8917/auth/oauth?method=signupWithGoogle"
```

I have another question around how to integrate both signup and login? Use different ENV var for each? I don't think using only one env var is gonna work becasue of the `/method=`. 

`Node: 20.11.1`
`@redwoodjs/core: 7.7.3 => 7.7.3`

**Comment by lyra-white** [comment]
Nevermind, i was setting redirect url to be the backend, it has to be frontend's function
